@startuml
'https://plantuml.com/sequence-diagram

autonumber

SystemServer -> AIDLName_Stub: new()
activate AIDLName_Stub
deactivate AIDLName_Stub
SystemServer -> ServiceManager: addService(keyName, AIDLName_Stub)
activate ServiceManager


@enduml