@startuml

box "WMS" #LightYellow
participant Session.java
participant WindowManagerService.java
participant WindowToken.java
participant WindowState.java
participant WindowStateAnimator.java
participant DisplayContent.java
participant DisplayContent.java_NonAppWindowContainers.java
end box

Session.java -> WindowManagerService.java: addWindow()
activate WindowManagerService.java

WindowManagerService.java -> WindowToken.java: new(token...)
activate WindowToken.java
note right
token vlue = ？
attrs.token != null ? attrs.token : client.asBinder();
cent = IWindow
end note

WindowToken.java -> WindowStateAnimator.java: new()
activate WindowStateAnimator.java
deactivate WindowStateAnimator.java
WindowToken.java -> WindowToken.java: onDisplayChanged()
activate WindowToken.java
WindowToken.java -> DisplayContent.java: reParentWindowToken(windowToken)
activate DisplayContent.java
DisplayContent.java -> DisplayContent.java: addWindowToken()
activate DisplayContent.java
DisplayContent.java -> DisplayContent.java: mTokenMap.put()
activate DisplayContent.java
deactivate DisplayContent.java
note left
update tokenMap:
mTokenMap.put(token, windowToken)
end note
DisplayContent.java -> DisplayContent.java_NonAppWindowContainers.java: addChild()
activate DisplayContent.java_NonAppWindowContainers.java
deactivate DisplayContent.java_NonAppWindowContainers.java
activate DisplayContent.java
deactivate DisplayContent.java
deactivate DisplayContent.java
deactivate DisplayContent.java
note left: add to mAboveAppWindowsContainers

deactivate WindowToken.java
deactivate WindowToken.java
deactivate WindowState.java

WindowManagerService.java -> WindowState.java: attach()
activate WindowState.java
deactivate WindowState.java
note left:AddWindow_2.1.1.0.puml

WindowManagerService.java -> WindowManagerService.java: mWindowMap.put(IWindow, (windowState))
activate WindowManagerService.java
deactivate WindowManagerService.java
note left
save IWindow-windowState
for match client&windowState
such as: process died to
remove windowState
end note

WindowManagerService.java -> WindowToken.java: addWindow(windowState)
activate WindowToken.java
deactivate WindowToken.java
deactivate WindowManagerService.java
note left:AddWindow_2.1.2.0.puml



@enduml