@startwbs
'https://plantuml.com/wbs-diagram

* ...
** Task(ContainerLayer)
*** animation-leash(EffectLayer)
**** ActivityRecord(ContainerLayer)
***** WindowState(ContainerLayer)
****** BufferQueueLayer
@endwbs