@startuml



 -> ActivityTaskManagerService.java: startProcessAsync()
activate ActivityTaskManagerService.java
ActivityTaskManagerService.java -> ActivityManagerService.java: startProcessLocked()
activate ActivityManagerService.java
ActivityManagerService.java -> ProcessList.java: startProcessLocked()
activate ProcessList.java
ProcessList.java -> ProcessList.java: newProcessRecordLocked()
activate ProcessList.java
deactivate ProcessList.java
ProcessList.java -> ProcessList.java: startProcessLocked()
activate ProcessList.java
ProcessList.java -> ProcessList.java: handleProcessStart()
activate ProcessList.java
ProcessList.java -> ProcessList.java: startProcess()
activate ProcessList.java
ProcessList.java -> Process.java: start()
activate Process.java
Process.java -> ZygoteProcess.java: start()
activate ZygoteProcess.java
ZygoteProcess.java -> ZygoteProcess.java: startViaZygote()
activate ZygoteProcess.java
ZygoteProcess.java -> ZygoteProcess.java: zygoteSendArgsAndGetResult()
activate ZygoteProcess.java
ZygoteProcess.java -> ZygoteProcess.java: attemptZygoteSendArgsAndGetResult()
activate ZygoteProcess.java
note left: write socket

@enduml