@startuml

box "Zygote" 
participant ZygoteServer.java
participant "ZygoteConnection(Zygote).java"
participant Zygote.java
end box

box "App" 
participant "ZygoteConnection(App).java"
participant ZygoteInit.java
participant RuntimeInit.java
participant ActivityThread.java
end box

box "AMS"
participant ActivityManagerService.java
end box

ZygoteServer.java -> ZygoteServer.java:runSelectLoop()
activate ZygoteServer.java
note left: read socket
ZygoteServer.java -> "ZygoteConnection(Zygote).java":processOneCommand()
activate "ZygoteConnection(Zygote).java"
"ZygoteConnection(Zygote).java" -> Zygote.java:forkAndSpecialize()
activate Zygote.java
Zygote.java -> Zygote.java:nativeForkAndSpecialize()
activate Zygote.java
deactivate Zygote.java
deactivate Zygote.java
"ZygoteConnection(Zygote).java" ->> "ZygoteConnection(App).java":handleChildProc()
activate "ZygoteConnection(App).java"
deactivate "ZygoteConnection(Zygote).java"
deactivate ZygoteServer.java
"ZygoteConnection(App).java" -> ZygoteInit.java:zygoteInit()
activate ZygoteInit.java
ZygoteInit.java -> RuntimeInit.java:commonInit()
activate RuntimeInit.java
deactivate RuntimeInit.java
note right
        catch exception logic

        LoggingHandler loggingHandler = new LoggingHandler();
        RuntimeHooks.setUncaughtExceptionPreHandler(loggingHandler);
        Thread.setDefaultUncaughtExceptionHandler(new KillApplicationHandler(loggingHandler));
end note
ZygoteInit.java -> ZygoteInit.java:nativeZygoteInit()
activate ZygoteInit.java
deactivate ZygoteInit.java
ZygoteInit.java -> RuntimeInit.java:applicationInit()
activate RuntimeInit.java
RuntimeInit.java -> RuntimeInit.java:findStaticMain()
activate RuntimeInit.java
RuntimeInit.java -> ActivityThread.java:main()
activate ActivityThread.java
ActivityThread.java -> ActivityThread.java:new()
activate ActivityThread.java
deactivate ActivityThread.java
ActivityThread.java -> ActivityThread.java:attach()
activate ActivityThread.java
ActivityThread.java ->> ActivityManagerService.java:attachApplication(applicationThread)
activate ActivityManagerService.java
deactivate ActivityThread.java
deactivate ActivityThread.java
deactivate ActivityThread.java
deactivate ZygoteInit.java
deactivate RuntimeInit.java
deactivate RuntimeInit.java
deactivate "ZygoteConnection(App).java"
ActivityManagerService.java -> ActivityManagerService.java:attachApplicationLocked()
activate ActivityManagerService.java
deactivate ActivityManagerService.java
deactivate ActivityManagerService.java

@enduml