@startuml

box "WMS"
participant WindowContainer_T.java
participant RootWindowContainer.java
participant SurfaceControl.java_Builder.java
participant SurfaceControl.java
participant TaskDisplayArea.java
participant TaskDisplayArea.java_Root.java
participant DisplayContent.java_WindowContainer.java
participant DisplayContent.java
participant WindowManagerService.java
participant WindowAnimator.java
end box

 -> WindowContainer_T.java: setParent()
activate WindowContainer_T.java
WindowContainer_T.java -> WindowContainer_T.java: onParentChanged()
activate WindowContainer_T.java
WindowContainer_T.java -> WindowContainer_T.java: createSurfaceControl()
activate WindowContainer_T.java
WindowContainer_T.java -> WindowContainer_T.java: makeSurface()
activate WindowContainer_T.java
deactivate WindowContainer_T.java
WindowContainer_T.java -> WindowContainer_T.java: setInitialSurfaceControlProperties()
activate WindowContainer_T.java
WindowContainer_T.java -> SurfaceControl.java_Builder.java: build()
activate SurfaceControl.java_Builder.java
deactivate SurfaceControl.java_Builder.java
WindowContainer_T.java -> SurfaceControl.java: new()
activate SurfaceControl.java
deactivate SurfaceControl.java
WindowContainer_T.java -> SurfaceControl.java: updateSurfacePosition()
activate SurfaceControl.java
deactivate SurfaceControl.java

deactivate WindowContainer_T.java
deactivate WindowContainer_T.java

WindowContainer_T.java -> WindowContainer_T.java: scheduleAnimation()
activate WindowContainer_T.java
WindowContainer_T.java -> TaskDisplayArea.java: scheduleAnimation()
activate TaskDisplayArea.java
TaskDisplayArea.java -> TaskDisplayArea.java_Root.java: scheduleAnimation()
activate TaskDisplayArea.java_Root.java
TaskDisplayArea.java_Root.java -> DisplayContent.java_WindowContainer.java: scheduleAnimation()
activate DisplayContent.java_WindowContainer.java
DisplayContent.java_WindowContainer.java -> DisplayContent.java: scheduleAnimation()
activate DisplayContent.java
DisplayContent.java -> RootWindowContainer.java: scheduleAnimation()
activate RootWindowContainer.java
RootWindowContainer.java -> WindowManagerService.java: scheduleAnimation()
activate WindowManagerService.java
WindowManagerService.java -> WindowAnimator.java: scheduleAnimation()
activate WindowAnimator.java

@enduml