@startuml
'https://plantuml.com/sequence-diagram

autonumber

-> SurfaceAnimationRunner.java: applyTransformation()
activate SurfaceAnimationRunner.java
SurfaceAnimationRunner.java -> WindowAnimationSpec.java: apply()
activate WindowAnimationSpec.java
WindowAnimationSpec.java -> AnimationSet.java: getTransformation()
activate AnimationSet.java

AnimationSet.java -> Animation.java: getTransformation()
activate Animation.java
Animation.java -> Animation.java: getTransformation()
activate Animation.java
Animation.java -> Interpolator.java: getInterpolation()
activate Interpolator.java
deactivate Interpolator.java
Animation.java -> Animation.java: applyTransformation()
activate Animation.java
deactivate Animation.java
deactivate Animation.java
deactivate Animation.java
deactivate AnimationSet.java

WindowAnimationSpec.java -> Transaction.java: setXXX()
activate Transaction.java
note left
setMatrix()
setAlpha()
setWindowCrop()
setCornerRadius()
end note

@enduml