@startuml
'https://plantuml.com/sequence-diagram

autonumber

Looper.java -> Looper.java : loop()
activate Looper.java
Looper.java -> Handler.java: dispatchMessage()
activate Handler.java
Handler.java -> Handler.java: handleCallback()
activate Handler.java
Handler.java -> "Choreographer$FrameDisplayEventReceiver.java": run()
activate "Choreographer$FrameDisplayEventReceiver.java"
"Choreographer$FrameDisplayEventReceiver.java"-> Choreographer.java :doFrame()
activate Choreographer.java
Choreographer.java -> Choreographer.java: doCallbacks()
activate Choreographer.java
Choreographer.java -> "Choreographer$CallbackRecord.java": run()
activate "Choreographer$CallbackRecord.java"
"Choreographer$CallbackRecord.java" -> SurfaceAnimationRunner.java: startAnimations()
activate SurfaceAnimationRunner.java
SurfaceAnimationRunner.java -> SurfaceAnimationRunner.java: startPendingAnimationsLocked()
activate SurfaceAnimationRunner.java
SurfaceAnimationRunner.java -> SurfaceAnimationRunner.java: startAnimationLocked()
activate SurfaceAnimationRunner.java

SurfaceAnimationRunner.java -> SfValueAnimator.java: new(0,1)
activate SfValueAnimator.java
deactivate SfValueAnimator.java
SurfaceAnimationRunner.java -> SfValueAnimator.java: addUpdateListener()
activate SfValueAnimator.java
deactivate SfValueAnimator.java
note left
applyTransformation()
end note

SurfaceAnimationRunner.java -> SfValueAnimator.java: start()
activate SfValueAnimator.java


@enduml