@startuml
'https://plantuml.com/class-diagram


class WindowManagerService {
SurfaceAnimationRunner mSurfaceAnimationRunner;
}

class SurfaceAnimationRunner {
ArrayMap<SurfaceControl, RunningAnimation> mPendingAnimations;
void startAnimations()
}
note right
new SurfaceAnimationRunner$SfValueAnimator
relay on mPendingAnimations
trigger animation
end note


class WindowState{
WindowStateAnimator mWinAnimator;
startAnimation()
}
note right
new LocalAnimationAdapter
new WindowAnimationSpec
end note

class LocalAnimationAdapter {
startAnimation()
}

note left
Animation that can be
executed without holding
 the window manager lock
end note
class SurfaceAnimator {
startAnimation()
}
note bottom
create animation leash
end note
class SurfaceAnimationRunner$RunningAnimation {

}
interface AnimationAdapter {
startAnimation()
}
class WindowAnimationSpec {

}
class ValueAnimator {

}
class SurfaceAnimationRunner$SfValueAnimator {

}
note bottom
animation driver

from 0 to 1
end note

class Transaction {

}
class SurfaceControl {

}
interface AnimationSpec{
}
class DisplayContent {
AppTransitionController mAppTransitionController
AppTransition mAppTransition
}

class WindowSurfacePlacer{
}
class WindowStateAnimator{
commitFinishDrawingLocked()
applyEnterAnimationLocked()
}

class WindowContainer {
startAnimation()
}

WindowManagerService *-> SurfaceAnimationRunner
WindowContainer *-right-> SurfaceAnimator
WindowState --|> WindowContainer
SurfaceAnimator *-right-> AnimationAdapter
LocalAnimationAdapter -up-|> AnimationAdapter
LocalAnimationAdapter *-right-> SurfaceAnimationRunner
LocalAnimationAdapter *-down-> AnimationSpec
SurfaceAnimationRunner ..> SurfaceAnimationRunner$RunningAnimation
SurfaceAnimationRunner ..> ValueAnimator
SurfaceAnimationRunner$RunningAnimation ..> AnimationSpec
SurfaceAnimationRunner$RunningAnimation *-> ValueAnimator
SurfaceAnimationRunner$SfValueAnimator -up-|> ValueAnimator
WindowAnimationSpec ..> Transaction
WindowAnimationSpec ..> SurfaceControl
WindowAnimationSpec -up-|> AnimationSpec

RootWindowContainer *-left-> DisplayContent
DisplayContent *..down.>  WindowStateAnimator
WindowState *-up-> WindowStateAnimator
WindowSurfacePlacer -down-> WindowManagerService
WindowManagerService *-left-> RootWindowContainer

@enduml