@startuml
'https://plantuml.com/class-diagram


class SystemServer {

}

class DisplayArea$Root {
    WindowList<DisplayArea> mChildren
    Dimmer mDimmer
}

class DisplayArea$Tokens {
    WindowList<WindowToken> mChildren
}


class ActivityStack {
    WindowList<WindowToken> mChildren
}

class ActivityRecord{
    IApplicationToken.Stub appToken
}

class WindowManagerService {
    RootWindowContainer mRoot;
}

class RootWindowContainer {
    WindowList<DisplayContent> mChildren
}


class DisplayContent {
    WindowContainers<WindowContainer> mWindowContainers
    NonAppWindowContainers mOverlayContainers
}

class WindowState {
    WindowToken mToken;
    ActivityRecord mActivityRecord;
}

class WindowContainer {
    WindowList<WindowContainer> mChildren
}

class DisplayContent$WindowContainers{
    WindowList<WindowContainer> mChildren
}

class TaskDisplayArea {
    WindowList<ActivityStack> mChildren
}

class DisplayArea {
    WindowList<WindowContainer> mChildren
}

class WindowToken {
    WindowList<WindowState> mChildren
}

class Task {
    WindowList<WindowContainer> mChildren
}

class DisplayContent$DisplayChildWindowContainer {
    WindowList<WindowContainer> mChildren
}

class DisplayContent$NonAppWindowContainers {
    WindowList<WindowToken> mChildren
}

abstract class ConfigurationContainer {
    Configuration mRequestedOverrideConfiguration
    Configuration mResolvedOverrideConfiguration
    Configuration mFullConfiguration
    Configuration mMergedOverrideConfiguration
}

note top
entry:
1.setBounds
2.onParentChanged

onRequestedOverrideConfigurationChanged
onConfigurationChanged
resolveOverrideConfiguration
onMergedOverrideConfigurationChanged
end note

WindowManagerService o--> RootWindowContainer
RootWindowContainer *--> DisplayContent
DisplayContent *--> DisplayContent$WindowContainers
DisplayContent *--> DisplayContent$NonAppWindowContainers
DisplayContent$WindowContainers *--> DisplayArea$Root
DisplayArea$Root *--> DisplayArea$Tokens
DisplayArea$Tokens *--> WindowToken
DisplayArea$Root *--> TaskDisplayArea
TaskDisplayArea *--> ActivityStack
ActivityStack *-->ActivityRecord
ActivityRecord *-right->WindowState
ConfigurationContainer <|-- WindowContainer
WindowContainer <|-- DisplayContent
WindowContainer <|-- DisplayContent$DisplayChildWindowContainer
WindowContainer <|-- DisplayArea
WindowContainer <|-- Task
WindowContainer <|-- WindowToken
WindowContainer <|-- WindowState
DisplayArea <|-- DisplayArea$Root
DisplayArea <|-- DisplayArea$Tokens
DisplayArea <|-- TaskDisplayArea
DisplayContent$DisplayChildWindowContainer <|-- DisplayContent$WindowContainers
DisplayContent$DisplayChildWindowContainer <|-- DisplayContent$NonAppWindowContainers
Task <|-- ActivityStack
WindowToken <|-- ActivityRecord
WindowToken *--> WindowState
@enduml