@startwbs
'https://plantuml.com/wbs-diagram
<style>
wbsDiagram {
  node {
      BackgroundColor LightYellow
  }
}
</style>
* RootWindowContainer
** DisplayContent0

*** DisplayContent$WindowContainers(mWindowContainers)0
**** DisplayArea$Root(mRootDisplayArea)
***** DisplayArea$Tokens(Leaf:0:1@BELOW_TASKS)0
****** WallpaperWindowToken
******* WindowState(Wallpaper)
***** DisplayArea$Tokens(Leaf:2:2@ANY)1
***** TaskDisplayArea(defaultTaskDisplayArea@ANY)2
****** ActivityStack (split-screen-secondary#4)
****** ActivityStack (split-screen-primary#3)
****** ActivityStack (home#1)
******* ActivityStack
******** ActivityRecord
********* WindowState(Activity)
********* WindowState(Dialog)
****** ActivityStack (fullscreen)
******* ActivityRecord
******** WindowState(Activity)
***** DisplayArea$Tokens(Leaf:3:14@ABOVE_TASKS)3
****** WindowToken
******* WindowState(SystemDialog)
****** WindowToken
***** ImeContainer(@ABOVE_TASKS)4
****** WindowToken
******* WindowState(InputMethod)
***** DisplayArea$Tokens(Leaf:17:34@ABOVE_TASKS)5
****** WindowToken
******* WindowState(StatusBar)
****** WindowToken
******* WindowState(Notification)
****** WindowToken
******* WindowState(NavigationBar)
****** WindowToken
******* WindowState(ScreenDecorOverlay)
****** WindowToken
******* WindowState(pip-dismiss-overlay)


*** DisplayContent$NonAppWindowContainers(mOverlayContainers@Screen-Magnification)1

** DisplayContent1

** DisplayContent...
@endwbs