@startuml
'https://plantuml.com/class-diagram

abstract ConfigurationContainer

class WindowContainer

class DisplayArea

class DisplayArea$Root

class DisplayContent




ConfigurationContainer <|-- WindowContainer



@enduml