@startuml

box "WMS"
participant Session.java
participant WindowManagerService.java
participant DisplayContent.java
participant WindowState.java
participant SurfaceAnimator.java
participant ActivityRecord.java
end box

Session.java -> WindowManagerService.java: addWindow()
activate WindowManagerService.java

WindowManagerService.java -> DisplayContent.java: getWindowToken()
activate DisplayContent.java
DisplayContent.java --> WindowManagerService.java: activityRecord
deactivate DisplayContent.java
note left: has created when ams startActivity
WindowManagerService.java -> WindowState.java: new(activityRecord ...)
activate WindowState.java
WindowState.java -> SurfaceAnimator.java: new()
activate SurfaceAnimator.java
deactivate SurfaceAnimator.java


deactivate WindowState.java

WindowManagerService.java -> WindowState.java: attach()
activate WindowState.java
deactivate WindowState.java
note left:AddWindow_2.1.1.0.puml

WindowManagerService.java -> WindowManagerService.java: mWindowMap.put(IWindow, (windowState))
activate WindowManagerService.java
deactivate WindowManagerService.java
note right
save IWindow-windowState
for match <ViewRootImpl_W> & <windowState>
end note


WindowManagerService.java -> ActivityRecord.java: addWindow(windowState)
activate ActivityRecord.java
deactivate ActivityRecord.java
deactivate WindowManagerService.java
note left:AddWindow_2.1.2.0.puml



@enduml