@startuml

box "WMS" #LightYellow
participant WindowManagerService.java
participant WindowState.java
participant Session.java
participant SurfaceSession.java
participant android_view_SurfaceSession.cpp
end box


WindowManagerService.java -> WindowState.java: attach()
activate WindowState.java

WindowState.java -> Session.java:windowAddedLocked()
activate Session.java

Session.java -> SurfaceSession.java:new()
activate SurfaceSession.java
note left
just first startup app need new.
when has been init just return
end note


SurfaceSession.java -> SurfaceSession.java:nativeCreate()
activate SurfaceSession.java

SurfaceSession.java -> android_view_SurfaceSession.cpp:nativeCreate()
activate android_view_SurfaceSession.cpp
deactivate android_view_SurfaceSession.cpp
deactivate SurfaceSession.java
deactivate SurfaceSession.java
deactivate WindowState.java
deactivate Session.java
note left:AddWindow_2.1.1.1.puml


@enduml