@startuml

box "WMS" #LightYellow
participant Session.java
participant WindowManagerService.java
participant DisplayContent.java
participant WindowState.java
participant SurfaceAnimator.java
participant AppWindowToken.java
end box

Session.java -> WindowManagerService.java: addWindow()
activate WindowManagerService.java


WindowManagerService.java -> DisplayContent.java: getAppWindowToken()
activate DisplayContent.java
note right
HashMap<IBinder, WindowToken> mTokenMap
Mapping from a token IBinder to a WindowToken object on this display.
end note
DisplayContent.java --> WindowManagerService.java: appWindowToken
deactivate DisplayContent.java
note left
different add different logic
this is activity add!!!
end note
WindowManagerService.java -> WindowState.java: new(appWindowToken ...)
activate WindowState.java
WindowState.java -> SurfaceAnimator.java: new()
activate SurfaceAnimator.java
deactivate SurfaceAnimator.java


deactivate WindowState.java

WindowManagerService.java -> WindowState.java: attach()
activate WindowState.java
deactivate WindowState.java
note left:AddWindow_2.1.1.0.puml

WindowManagerService.java -> AppWindowToken.java: addWindow(windowState)
activate AppWindowToken.java
deactivate AppWindowToken.java
deactivate WindowManagerService.java
note left:AddWindow_2.1.2.0.puml



@enduml