@startuml
box "App" #LightYellow
participant Activity.java
participant ContextImpl.java
participant SystemServiceRegistry.java
participant CachedServiceFetcher.java
participant WindowManagerImpl.java
end box

-> Activity.java: getSystemService()
activate Activity.java
Activity.java --> ContextImpl.java: getSystemService()
activate ContextImpl.java
ContextImpl.java --> SystemServiceRegistry.java: getSystemService()
activate SystemServiceRegistry.java
SystemServiceRegistry.java --> CachedServiceFetcher.java: createService()
activate CachedServiceFetcher.java
CachedServiceFetcher.java --> WindowManagerImpl.java: new()
activate WindowManagerImpl.java
deactivate CachedServiceFetcher.java
deactivate SystemServiceRegistry.java
deactivate ContextImpl.java
deactivate Activity.java
deactivate WindowManagerImpl.java

-> WindowManagerImpl.java: addView()
note left:AddWindow_2.0.0.0.puml
activate WindowManagerImpl.java


@enduml