@startuml

box "WMS" #LightYellow
participant Session.java
participant WindowManagerService.java
participant WindowStateAnimator.java
participant WindowSurfaceController.java
participant "SurfaceControl$Builder.java"
participant SurfaceControl.java
participant android_view_SurfaceControl.cpp
participant SurfaceComposerClient.cpp
participant SurfaceControl.cpp
participant SurfaceControl.cpp
end box

box "SurfaceFlinger" #LightYellow
participant Client.cpp
participant SurfaceFlinger.cpp
participant BufferQueueLayer.cpp
end box

->  Session.java : relayout()
activate Session.java
Session.java -> WindowManagerService.java: relayoutWindow()
activate WindowManagerService.java
WindowManagerService.java -> WindowManagerService.java: createSurfaceControl()
activate WindowManagerService.java
WindowManagerService.java -> WindowStateAnimator.java: createSurfaceLocked()
activate WindowStateAnimator.java
note left: 1. create
WindowStateAnimator.java -> WindowSurfaceController.java: new()
activate WindowSurfaceController.java
WindowSurfaceController.java -> "SurfaceControl$Builder.java": build()
activate "SurfaceControl$Builder.java"
"SurfaceControl$Builder.java" -> SurfaceControl.java: new()
activate SurfaceControl.java
SurfaceControl.java -> SurfaceControl.java: nativeCreate()
activate SurfaceControl.java
SurfaceControl.java -> android_view_SurfaceControl.cpp: nativeCreate()
activate android_view_SurfaceControl.cpp
android_view_SurfaceControl.cpp -> SurfaceComposerClient.cpp: createSurfaceChecked()
activate SurfaceComposerClient.cpp
SurfaceComposerClient.cpp -> Client.cpp: createSurface()
activate Client.cpp
Client.cpp -> SurfaceFlinger.cpp: createLayer()
activate SurfaceFlinger.cpp
SurfaceFlinger.cpp -> SurfaceFlinger.cpp: createBufferQueueLayer()
activate SurfaceFlinger.cpp
SurfaceFlinger.cpp -> BufferQueueLayer.cpp: new()
activate BufferQueueLayer.cpp
deactivate BufferQueueLayer.cpp
deactivate SurfaceFlinger.cpp
deactivate SurfaceFlinger.cpp
deactivate Client.cpp
deactivate Client.cpp
SurfaceComposerClient.cpp -> SurfaceControl.cpp: new(handle, gbp)
activate SurfaceControl.cpp
deactivate SurfaceControl.cpp
deactivate SurfaceComposerClient.cpp
deactivate android_view_SurfaceControl.cpp
deactivate SurfaceControl.java
deactivate SurfaceControl.java
deactivate "SurfaceControl$Builder.java"
deactivate WindowSurfaceController.java
deactivate WindowStateAnimator.java

WindowManagerService.java -> WindowSurfaceController.java:getSurfaceControl(outSurfaceControl)
activate WindowSurfaceController.java
note left: 2. copy
WindowSurfaceController.java -> SurfaceControl.java:copyFrom()
activate SurfaceControl.java
deactivate SurfaceControl.java
deactivate WindowSurfaceController.java
deactivate WindowManagerService.java
deactivate WindowManagerService.java
deactivate Session.java

@enduml