@startuml

box "WMS" #LightYellow
participant ActivityRecord.java
participant WindowState.java
participant DisplayContent.java
participant SurfaceControl.java_Builder.java
participant SurfaceControl.java
participant android_view_SurfaceControl.cpp
participant SurfaceComposerClient.cpp
end box

box "SurfaceFlinger" #LightYellow
participant Client.cpp
participant SurfaceFlinger.cpp
end box

ActivityRecord.java -> ActivityRecord.java: addWindow(WindowState)
activate ActivityRecord.java
ActivityRecord.java -> ActivityRecord.java: addChild(WindowState)
activate ActivityRecord.java
ActivityRecord.java -> ActivityRecord.java: makeSurface()
activate ActivityRecord.java
ActivityRecord.java -> WindowState.java: setParent()
activate WindowState.java
WindowState.java -> WindowState.java: onParentChanged()
activate WindowState.java
WindowState.java -> WindowState.java: createSurfaceControl()
activate WindowState.java
WindowState.java -> WindowState.java: makeSurface()
activate WindowState.java
WindowState.java -> DisplayContent.java: makeChildSurface()
activate DisplayContent.java
DisplayContent.java -> SurfaceControl.java_Builder.java: new()
activate SurfaceControl.java_Builder.java
deactivate SurfaceControl.java_Builder.java
deactivate DisplayContent.java
WindowState.java -> SurfaceControl.java_Builder.java: build()
activate SurfaceControl.java_Builder.java
SurfaceControl.java_Builder.java -> SurfaceControl.java: new()
activate SurfaceControl.java
SurfaceControl.java -> SurfaceControl.java: nativeCreate()
activate SurfaceControl.java
SurfaceControl.java -> android_view_SurfaceControl.cpp: nativeCreate()
activate android_view_SurfaceControl.cpp
android_view_SurfaceControl.cpp -> SurfaceComposerClient.cpp: createSurfaceChecked()
activate SurfaceComposerClient.cpp
SurfaceComposerClient.cpp -> Client.cpp: createSurface()
activate Client.cpp
Client.cpp -> SurfaceFlinger.cpp: createLayer()
activate SurfaceFlinger.cpp
activate Client.cpp

deactivate Client.cpp
deactivate Client.cpp
deactivate SurfaceFlinger.cpp

deactivate android_view_SurfaceControl.cpp
deactivate SurfaceComposerClient.cpp
deactivate SurfaceControl.java
deactivate SurfaceControl.java
deactivate SurfaceControl.java_Builder.java
deactivate ActivityRecord.java
deactivate ActivityRecord.java
deactivate ActivityRecord.java
deactivate ActivityRecord.java
deactivate ActivityRecord.java
deactivate ActivityRecord.java



@enduml