@startuml

box "App" #LightYellow
participant ActivityThread.java
participant Activity.java
participant PhoneWindow.java
participant ContextImpl.java
participant SystemServiceRegistry.java
participant SystemServiceRegistry.java_CachedServiceFetcher.java
participant WindowManagerImpl.java
end box

ActivityThread.java -> Activity.java:attach()
activate Activity.java
Activity.java -> PhoneWindow.java:new()
activate PhoneWindow.java


deactivate PhoneWindow.java
Activity.java -> PhoneWindow.java:setCallback(activity)
activate PhoneWindow.java
deactivate PhoneWindow.java

Activity.java -> ContextImpl.java:getSystemService()
activate ContextImpl.java
ContextImpl.java -> SystemServiceRegistry.java:getSystemService(contextImpl)
activate SystemServiceRegistry.java
SystemServiceRegistry.java -> SystemServiceRegistry.java_CachedServiceFetcher.java:getSystemService(contextImpl)
activate SystemServiceRegistry.java_CachedServiceFetcher.java
SystemServiceRegistry.java_CachedServiceFetcher.java -> SystemServiceRegistry.java_CachedServiceFetcher.java:createService(contextImpl)
activate SystemServiceRegistry.java_CachedServiceFetcher.java
SystemServiceRegistry.java_CachedServiceFetcher.java -> WindowManagerImpl.java:new(contextImpl)
activate WindowManagerImpl.java

Activity.java -> PhoneWindow.java:setWindowManager(token...)
activate PhoneWindow.java

@enduml