@startuml
Binder -> ActivityTaskManagerService.java: activityPaused()
activate ActivityTaskManagerService.java
ActivityTaskManagerService.java --> ActivityStack.java: activityPausedLocked()
activate ActivityStack.java
ActivityStack.java --> ActivityStack.java: completePauseLocked()
activate ActivityStack.java
ActivityStack.java --> RootActivityContainer.java: resumeFocusedStackTopActivityLocked()
activate RootActivityContainer.java
RootActivityContainer.java --> ActivityStack.java: resumeTopActivityUncheckedLocked()
activate ActivityStack.java
ActivityStack.java --> ActivityStack.java: resumeTopActivityInnerLocked()
activate ActivityStack.java
ActivityStack.java --> RootActivityContainer.java: ensureVisibilityAndConfig()
activate RootActivityContainer.java
RootActivityContainer.java --> RootActivityContainer.java: ensureActivitiesVisible()
activate RootActivityContainer.java
RootActivityContainer.java --> ActivityDisplay.java: ensureActivitiesVisible()
activate ActivityDisplay.java
ActivityDisplay.java --> ActivityStack.java: ensureActivitiesVisibleLocked()
activate ActivityStack.java
ActivityStack.java --> ActivityStack.java: shouldBeVisible()
activate ActivityStack.java
ActivityStack.java --> ActivityStack.java: getVisibility()
activate ActivityStack.java
ActivityStack.java --> ActivityStack.java: isStackTranslucent()
activate ActivityStack.java

@enduml