@startuml

box "AMS" #LightYellow
participant ActivityStackSupervisor
participant ActivityDisplay
participant ActivityStack
participant ClientLifecycleManager
end box

box "WMS"  #LightYellow
participant WindowManagerService
participant WindowSurfacePlacer
participant AppWindowToken
participant SurfaceAnimator
participant SurfaceControl
participant DisplayContent
participant TaskStack
participant TaskStackContainers
participant RootWindowContainer

end box


ActivityStack -> ActivityStackSupervisor:ensureActivitiesVisibleLocked()
activate ActivityStackSupervisor
note left: process进程存在
ActivityStackSupervisor -> ActivityStack:ensureActivitiesVisibleLocked()
activate ActivityStack
ActivityStack -> ActivityStack:makeInvisible()
activate ActivityStack
ActivityStack -> ActivityStack:addToStopping()
activate ActivityStack
ActivityStack -> ActivityStackSupervisor:scheduleIdleLocked()
activate ActivityStackSupervisor
ActivityStackSupervisor -> ActivityStackSupervisor:activityIdleInternalLocked()
activate ActivityStackSupervisor
ActivityStackSupervisor -> ActivityStack:stopActivityLocked()
activate ActivityStack
ActivityStack -> ClientLifecycleManager:scheduleTransaction(StopActivityItem)
activate ClientLifecycleManager
deactivate ClientLifecycleManager
deactivate ActivityStack
deactivate ActivityStack
deactivate ActivityStack
deactivate ActivityStack
deactivate ActivityStack
deactivate ActivityStackSupervisor
deactivate ActivityStackSupervisor
deactivate ActivityStackSupervisor


ActivityStack -> WindowManagerService:continueSurfaceLayout()
activate WindowManagerService
WindowManagerService -> WindowSurfacePlacer:continueLayout()
activate WindowSurfacePlacer
WindowSurfacePlacer -> WindowSurfacePlacer:performSurfacePlacement()
activate WindowSurfacePlacer
WindowSurfacePlacer -> WindowSurfacePlacer:performSurfacePlacementLoop()
activate WindowSurfacePlacer
WindowSurfacePlacer -> RootWindowContainer:performSurfacePlacement()
activate RootWindowContainer
RootWindowContainer -> WindowSurfacePlacer:handleAppTransitionReadyLocked()
activate WindowSurfacePlacer
WindowSurfacePlacer -> WindowSurfacePlacer:handleClosingApps()
activate WindowSurfacePlacer
WindowSurfacePlacer -> AppWindowToken:setVisibility()
activate AppWindowToken
AppWindowToken -> AppWindowToken:applyAnimationLocked()
activate AppWindowToken
AppWindowToken -> SurfaceAnimator:startAnimation()
activate SurfaceAnimator
SurfaceAnimator -> AppWindowToken:onAnimationLeashCreated()
activate AppWindowToken
AppWindowToken -> AppWindowToken:getPrefixOrderIndex()
activate AppWindowToken
AppWindowToken -> SurfaceControl:setLayer()
activate SurfaceControl
AppWindowToken -> DisplayContent:assignStackOrdering()
activate DisplayContent
DisplayContent -> TaskStackContainers:assignStackOrdering()
activate TaskStackContainers
deactivate TaskStackContainers
deactivate DisplayContent
deactivate SurfaceControl
deactivate SurfaceAnimator
deactivate AppWindowToken
deactivate AppWindowToken
deactivate AppWindowToken
deactivate AppWindowToken
deactivate WindowSurfacePlacer




WindowSurfacePlacer -> WindowSurfacePlacer:handleOpeningApps()
activate WindowSurfacePlacer
WindowSurfacePlacer -> AppWindowToken:setVisibility()
activate AppWindowToken
AppWindowToken -> AppWindowToken:applyAnimationLocked()
activate AppWindowToken
AppWindowToken -> SurfaceAnimator:startAnimation()
activate SurfaceAnimator
SurfaceAnimator -> AppWindowToken:onAnimationLeashCreated()
activate AppWindowToken
AppWindowToken -> AppWindowToken:getPrefixOrderIndex()
activate AppWindowToken
AppWindowToken -> SurfaceControl:setLayer()
activate SurfaceControl
AppWindowToken -> DisplayContent:assignStackOrdering()
activate DisplayContent
DisplayContent -> TaskStackContainers:assignStackOrdering()
activate TaskStackContainers
deactivate TaskStackContainers
deactivate DisplayContent
deactivate SurfaceControl
deactivate SurfaceAnimator
deactivate AppWindowToken
deactivate AppWindowToken
deactivate AppWindowToken
deactivate AppWindowToken
deactivate WindowSurfacePlacer
deactivate WindowSurfacePlacer
deactivate WindowSurfacePlacer
deactivate WindowSurfacePlacer
deactivate WindowSurfacePlacer
deactivate RootWindowContainer
deactivate WindowManagerService
deactivate ActivityStack


@enduml