@startuml
box "App" #LightYellow
participant targetView.java
participant ViewRootImpl.java
participant Choreographer.java
participant Surface.java
end box

box "WMS" #LightYellow
participant Session.java
participant WindowManagerService.java
end box

targetView.java -> ViewRootImpl.java: requestLayout()
activate ViewRootImpl.java
ViewRootImpl.java -> ViewRootImpl.java: requestLayout()
activate ViewRootImpl.java
ViewRootImpl.java -> ViewRootImpl.java: scheduleTraversals()
activate ViewRootImpl.java
ViewRootImpl.java -> Choreographer.java: postCallback(Choreographer.CALLBACK_TRAVERSAL)
activate Choreographer.java
deactivate Choreographer.java
deactivate ViewRootImpl.java
deactivate ViewRootImpl.java
deactivate ViewRootImpl.java
deactivate WindowManagerService.java
deactivate Session.java
deactivate targetView.java

Choreographer.java -> Choreographer.java: doFrame()
activate Choreographer.java
Choreographer.java -> Choreographer.java: doCallbacks()
activate Choreographer.java
Choreographer.java -> ViewRootImpl.java: doTraversal()
activate ViewRootImpl.java

ViewRootImpl.java -> ViewRootImpl.java: performTraversals()
activate ViewRootImpl.java
ViewRootImpl.java -> ViewRootImpl.java: relayoutWindow()
activate ViewRootImpl.java
ViewRootImpl.java -> Session.java: relayout()
activate Session.java
note left: 首帧绘制 get surface
Session.java -> WindowManagerService.java: relayoutWindow()
activate WindowManagerService.java
deactivate WindowManagerService.java
deactivate Session.java
ViewRootImpl.java -> Surface.java:copyFrom()
activate Surface.java
Surface.java -> Surface.java:nativeGetFromSurfaceControl()
activate Surface.java
deactivate Surface.java
deactivate Surface.java
deactivate ViewRootImpl.java

ViewRootImpl.java -> ViewRootImpl.java: performMeasure()
note left: 1 measure
activate ViewRootImpl.java
deactivate ViewRootImpl.java
ViewRootImpl.java -> ViewRootImpl.java: performLayout()
note left: 2 layout
activate ViewRootImpl.java
deactivate ViewRootImpl.java
ViewRootImpl.java -> ViewRootImpl.java: performDraw()
note left: 3 draw
activate ViewRootImpl.java
ViewRootImpl.java -> ViewRootImpl.java: draw()
activate ViewRootImpl.java
deactivate ViewRootImpl.java


@enduml